
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::6}
before_install:
#  - npm install -g @angular/cli
sudo: required
services:
- docker
script:
- export REPO=mayadata/www-mayadata-io;
- docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -t $REPO:$TRAVIS_BRANCH-$COMMIT . ;
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then export REPO=mayadata/www-mayadata-io;
   docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -t $REPO:$COMMIT . && docker push $REPO; 
  fi
- if [ "$TRAVIS_BRANCH" = "staging" -a "$TRAVIS_PULL_REQUEST" != "false" ]; then export REPO=mayadata/www-staging-mayadata-io;
   docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -t $REPO:$TRAVIS_BRANCH-$COMMIT . && docker push $REPO; 
  fi
- if [ "$TRAVIS_BRANCH" = "dev-staging" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then export REPO=mayadata/dev-staging-mayadata;
   docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -t $REPO:$COMMIT . && docker push $REPO; 
  fi
- if [ "$TRAVIS_BRANCH" = "dev-kubecon" -a "$TRAVIS_PULL_REQUEST" != "false" ]; then export REPO=mayadata/dev-staging-mayadata;
   docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -t $REPO:$COMMIT . && docker push $REPO; 
  fi
