import { GTM } from "../constants/constants"
import { HANDSONS } from "../constants/content-types"

export const handsons = [
  // {
  //   title: 'Using OpenEBS as TSDB for Prometheus',
  //   logo: 'assets/images/workloads/prometheus.png',
  //   modalDataTarget: 'prometheus',
  //   image_url: 'assets/images/resources/hands-ons/hands-on-1.png',
  //   image_alt: 'Hands-On',
  //   actionText: 'Read More',
  //   externalLink: false,
  //      className: GTM.TRIGGERS.HANDSONS,
  // type: HANDSONS
  // },
  {
    title: 'OpenEBS for GitLab',
    logo: 'assets/images/workloads/gitlab.png',
    modalDataTarget: 'gitlab',
    image_url: 'assets/images/resources/hands-ons/hands-on-2.png',
    image_alt: 'Hands-On',
    actionText: 'Read More',
    externalLink: false,
    className: GTM.TRIGGERS.HANDSONS,
    type: HANDSONS,
    name: 'Hands&#8209;On'
  },
  // {
  //   title: 'Deploy Cassandra on Kubernetes using OpenEBS',
  //   logo: 'assets/images/workloads/cassandra.png',
  //   modalDataTarget: 'cassandra',
  //   image_url: 'assets/images/resources/hands-ons/hands-on-3.png',
  //   image_alt: 'Hands-On',
  //   actionText: 'Read More',
  //   externalLink: false,
  //      className: GTM.TRIGGERS.HANDSONS,
  // type: HANDSONS
  // },
  // {
  //   title: 'OpenEBS for Minio',
  //   logo: 'assets/images/workloads/minio.png',
  //   modalDataTarget: 'minio',
  //   image_url: 'assets/images/resources/hands-ons/hands-on-1.png',
  //   image_alt: 'Hands-On',
  //   actionText: 'Read More',
  //   externalLink: false,
  //      className: GTM.TRIGGERS.HANDSONS,
  //  type: HANDSONS
  // },
  {
    title: 'OpenEBS for Redis',
    logo: 'assets/images/workloads/redis.png',
    modalDataTarget: 'redis',
    image_url: 'assets/images/resources/hands-ons/hands-on-2.png',
    image_alt: 'Hands-On',
    actionText: 'Read More',
    externalLink: false,
    className: GTM.TRIGGERS.HANDSONS,
    type: HANDSONS,
    name: 'Hands&#8209;On'
  },
  {
    title: 'Provisioning Read-Write-Many (RWM) PVCs',
    logo: 'assets/images/workloads/nfs.png',
    modalDataTarget: 'nfs',
    image_url: 'assets/images/resources/hands-ons/hands-on-3.png',
    image_alt: 'Hands-On',
    actionText: 'Read More',
    externalLink: false,
    className: GTM.TRIGGERS.HANDSONS,
    type: HANDSONS,
    name: 'Hands&#8209;On'
  },
  {
    title: 'Managed database service like RDS',
    logo: 'assets/images/workloads/mysql.png',
    modalDataTarget: 'mysql',
    image_url: 'assets/images/resources/hands-ons/hands-on-1.png',
    image_alt: 'Hands-On',
    actionText: 'Read More',
    externalLink: false,
    className: GTM.TRIGGERS.HANDSONS,
    type: HANDSONS,
    name: 'Hands&#8209;On'
  },
  {
    title: 'OpenEBS for PostgreSQL',
    logo: 'assets/images/workloads/postgresql.png',
    modalDataTarget: 'postgresql',
    image_url: 'assets/images/resources/hands-ons/hands-on-2.png',
    image_alt: 'Hands-On',
    actionText: 'Read More',
    externalLink: false,
    className: GTM.TRIGGERS.HANDSONS,
    type: HANDSONS,
    name: 'Hands&#8209;On'
  },
  {
    title: 'OpenEBS for Percona',
    logo: 'assets/images/workloads/percona.png',
    modalDataTarget: 'percona',
    image_url: 'assets/images/resources/hands-ons/hands-on-3.png',
    image_alt: 'Hands-On',
    actionText: 'Read More',
    externalLink: false,
    className: GTM.TRIGGERS.HANDSONS,
    type: HANDSONS,
    name: 'Hands&#8209;On'
  },
  {
    title: 'OpenEBS for NuoDB',
    logo: 'assets/images/workloads/nuodb.png',
    modalDataTarget: 'nuodb',
    image_url: 'assets/images/resources/hands-ons/hands-on-1.png',
    image_alt: 'Hands-On',
    actionText: 'Read More',
    externalLink: false,
    className: GTM.TRIGGERS.HANDSONS,
    type: HANDSONS,
    name: 'Hands&#8209;On'
  },
  {
    title: 'OpenEBS for MongoDB',
    logo: 'assets/images/workloads/mongodb.png',
    modalDataTarget: 'mongodb',
    image_url: 'assets/images/resources/hands-ons/hands-on-2.png',
    image_alt: 'Hands-On',
    actionText: 'Read More',
    externalLink: false,
    className: GTM.TRIGGERS.HANDSONS,
    type: HANDSONS,
    name: 'Hands&#8209;On'
  },
  {
    title: 'Deploying Kafka on Kubernetes',
    logo: 'assets/images/workloads/kafka.svg',
    modalDataTarget: false,
    url: '/workloads/kafka-on-kubernetes',
    image_url: 'assets/images/resources/hands-ons/hands-on-3.png',
    image_alt: 'Hands-On',
    actionText: 'Read More',
    externalLink: true,
    className: GTM.TRIGGERS.HANDSONS,
    type: HANDSONS,
    name: 'Hands&#8209;On'
  },
  {
    title: 'Deploying ElasticSearch / EFK on Kubernetes',
    logo: 'assets/images/workloads/elasticsearch.png',
    modalDataTarget: false,
    url: '/workloads/elasticsearch-on-kubernetes',
    image_url: 'assets/images/resources/hands-ons/hands-on-1.png',
    image_alt: 'Hands-On',
    actionText: 'Read More',
    externalLink: true,
    className: GTM.TRIGGERS.HANDSONS,
    type: HANDSONS,
    name: 'Hands&#8209;On'
  },
  {
    title: 'Deploying Magento on Kubernetes',
    logo: 'assets/images/workloads/magento.png',
    modalDataTarget: false,
    url: '/workloads/magento-on-kubernetes',
    image_url: 'assets/images/resources/hands-ons/hands-on-2.png',
    image_alt: 'Hands-On',
    actionText: 'Read More',
    externalLink: true,
    className: GTM.TRIGGERS.HANDSONS,
    type: HANDSONS,
    name: 'Hands&#8209;On'
  },
  {
    title: 'Deploying Cassandra on Kubernetes',
    logo: 'assets/images/workloads/cassandra.png',
    modalDataTarget: false,
    url: '/workloads/cassandra-on-kubernetes',
    image_url: 'assets/images/resources/hands-ons/hands-on-3.png',
    image_alt: 'Hands-On',
    actionText: 'Read More',
    externalLink: true,
    className: GTM.TRIGGERS.HANDSONS,
    type: HANDSONS,
    name: 'Hands&#8209;On'
  },
  {
    title: 'Deploying MinIO on Kubernetes',
    logo: 'assets/images/workloads/minio.png',
    modalDataTarget: false,
    url: '/workloads/minio-on-kubernetes',
    image_url: 'assets/images/resources/hands-ons/hands-on-1.png',
    image_alt: 'Hands-On',
    actionText: 'Read More',
    externalLink: true,
    className: GTM.TRIGGERS.HANDSONS,
    type: HANDSONS,
    name: 'Hands&#8209;On'
  },
  {
    title: 'Deploying Prometheus on Kubernetes',
    logo: 'assets/images/workloads/prometheus.png',
    modalDataTarget: false,
    url: '/workloads/prometheus-on-kubernetes',
    image_url: 'assets/images/resources/hands-ons/hands-on-2.png',
    image_alt: 'Hands-On',
    actionText: 'Read More',
    externalLink: true,
    className: GTM.TRIGGERS.HANDSONS,
    type: HANDSONS,
    name: 'Hands&#8209;On'
  },
]
